name: Deploy React Web (MIZAN EXPERT GROUP) to VDS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: .

      # Uncomment if you want to run tests
      # - name: Run tests
      #   run: npm test -- --watchAll=false
      #   working-directory: .

      - name: Build project (log output)
        run: |
          cp .env.production .env
          CI=false npm run build | tee build-logs.txt
        working-directory: .

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: react-web-build-logs
          path: mizangroup_uz/build-logs.txt

      - name: Deploy to VDS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.VDS_SSH_KEY }}
          source: "mizangroup_uz/build/*"
          target: "~/mizangroup_uz/web"

      - name: Restart Nginx
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.VDS_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
